version: 0.2

phases:
  install:
    commands:
      - npm i npm@8.19.4 -g
      - node -v
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - rm package-lock.json
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Build Phase
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync ./dist s3://saju-front-prod-1209
